### ISSUE TITLE
Ad selection issues in block

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-ads#1]
I noticed a few small issues when testing out the ad block:

### 1.

Ads without dimensions or with dimensions that don't parse don't look nice when the preview is rendered in the editor. It's probably best to have a nice min value for the preview dimensions. It'll be weird to manage  pixel-based ad codes (ad codes with dimensions of 1x1 or no dimension) if there isn't a minimum on the preview. You may also want to display some sort of error notice in the block if the code doesn't look like a valid ad code (e.g. dimension parsing fails).

![localhost_wp-admin_post php_post=1 action=edit (2)](https://user-images.githubusercontent.com/7317227/61152376-1fb09e00-a49d-11e9-99dd-84cb13b6c778.png)

**To reproduce: Enter an invalid ad code for an ad unit.**

### 2

If you only have one ad code, it's impossible to select it. Also, to select the first ad code you must first select a different ad code and then select the first ad code. If while fixing this, you really want the block to initialize with the "Select an ad unit" text instead of selected on the first ad code, I recommend making the first select option "Select an ad code" instead of the first code.

![localhost_wp-admin_post php_post=1 action=edit (3)](https://user-images.githubusercontent.com/7317227/61152382-217a6180-a49d-11e9-8b38-06d005ee13fc.png)

**To reproduce: Only have one ad code defined and try to select it.**
**To reproduce: Have multiple ad codes defined and try to select the first one in the select menu.**

### 3

This isn't a technical issue, but it took me like 15 minutes of debugging to realize that the select dialogue is in the sidebar and not to expect a select dropdown in the block itself. The "Select an ad unit" text in the block really makes it seem like there should be a select right there. My suggestion is to either change the text to something like "Select an ad unit from the block settings in the sidebar" or have the select be within the block.

**To reproduce: Erase all memories of using the block. Try and use the block. :)**

### 4

There is no handling for when no ad units are defined. When no ad units exist, I recommend changing the text from "Select an ad unit" to something like "No ad units have been created yet. [You can create ad units in the Ad Manager wizard](https://www.example.com/linktoadmanagerwizard)".

**To reproduce: Delete all your ad units and insert the block.**

**Comment by philipjohn** [comment]
> If you only have one ad code, it's impossible to select it.

This is related to [this Gutenberg bug](https://github.com/WordPress/gutenberg/issues/11270)

**Comment by sonjaleix** [comment]
For **3**. maybe we can move the selector into the ad block UI. This contextual implementation would very helpful, especially because the ad unit selector doesn't appear in the block sidebar controls until you click on the block. I did a quick mockup: 
<img width="400" alt="Screenshot 2019-07-15 17 14 12" src="https://user-images.githubusercontent.com/4823744/61255429-bdb69980-a725-11e9-9127-f1469f375456.png">
We would need to build in error messages / warnings when a user has added an ad unit but hasn't selected a unit. It would probably be good to display these errors/warnings when a post/page with undefined ad units is trying to be published. This also relates to recommendation **4.**, which is a good idea.

**Comment by jeffersonrabb** [comment]
> There is no handling for when no ad units are defined. When no ad units exist, I recommend changing the text from "Select an ad unit" to something like "No ad units have been created yet. You can create ad units in the Ad Manager wizard".

Great idea. Done in https://github.com/Automattic/newspack-ads/commit/203c740f8a57dd672ddd7c5028f9149be08c3ae0.

**Comment by jeffersonrabb** [comment]
> This isn't a technical issue, but it took me like 15 minutes of debugging to realize that the select dialogue is in the sidebar and not to expect a select dropdown in the block itself. The "Select an ad unit" text in the block really makes it seem like there should be a select right there. My suggestion is to either change the text to something like "Select an ad unit from the block settings in the sidebar" or have the select be within the block.

Did this in https://github.com/Automattic/newspack-ads/commit/7106db9ff2b044b5cf663fc37a2fdef4054c9bac

**Comment by jeffersonrabb** [comment]
> If you only have one ad code, it's impossible to select it. Also, to select the first ad code you must first select a different ad code and then select the first ad code. If while fixing this, you really want the block to initialize with the "Select an ad unit" text instead of selected on the first ad code, I recommend making the first select option "Select an ad code" instead of the first code.

This is done in https://github.com/Automattic/newspack-ads/commit/7106db9ff2b044b5cf663fc37a2fdef4054c9bac. It's not perfect — ideally the first item in the SelectControl would be disabled, but this isn't an option yet.

**Comment by jeffersonrabb** [comment]
> Ads without dimensions or with dimensions that don't parse don't look nice when the preview is rendered in the editor. It's probably best to have a nice min value for the preview dimensions. It'll be weird to manage pixel-based ad codes (ad codes with dimensions of 1x1 or no dimension) if there isn't a minimum on the preview. 

This still needs work, but let's track it in https://github.com/Automattic/newspack-ads/issues/5 since the nature of the problem has evolved (due to moving the Select onto the block).

**Comment by jeffersonrabb** [comment]
> You may also want to display some sort of error notice in the block if the code doesn't look like a valid ad code (e.g. dimension parsing fails).

Done in https://github.com/Automattic/newspack-ads/commit/8a25b41e3b1353ce19cd2075e940caf96f1b1581
