### ISSUE TITLE
[ON HOLD] Ad Unit Block: Add support for AdSense

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-ads#104]
It's currently only possible to add an AdSense unit in the pre-defined global placements. It is not possible to add AdSense ads via the Ad Unit block, where only Google Ad Manager ads are exposed.

To get around this limitation, publishers need to have a Google Ad Manager account and an ad unit serving AdSense that they can then drop into their site using the Ad Unit block. Using GAM is not easy for the average publisher and is a huge learning curve if they only want to serve AdSense (and not use Auto Ads).

Adding AdSense support to the Ad Unit block would alleviate a lot of work for smaller publishers.

**Comment by kmwilkerson** [comment]
Same comment as on issue #117

**Comment by kmwilkerson** [comment]
Closing in favor of managing AdSense via GAM. AdSense auto ads will still be available via SiteKit.
