### ISSUE TITLE
Ad Unit Widget: Add support for AdSense

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-ads#105]
It's currently only possible to add an AdSense unit in the pre-defined global placements. It is not possible to add AdSense ads via the Ad Unit widget, where only Google Ad Manager ads are exposed.

To get around this limitation, publishers need to have a Google Ad Manager account and an ad unit serving AdSense that they can then drop into their site using the Ad Unit widget. Using GAM is not easy for the average publisher and is a huge learning curve if they only want to serve AdSense (and not use Auto Ads).

Adding AdSense support to the Ad Unit widget would alleviate a lot of work for smaller publishers.

**Comment by claudiulodro** [comment]
With WP 5.8's block-widgets, this won't be needed if we have AdSense support in the block :D
