### ISSUE TITLE
Can't see all ad units if >100 ad units

### ISSUE THREAD

**Issue by idpsolutions** [Automattic/newspack-ads#106]
We have a list of Ad units that we need to use in our website. At some point, it seems that there is a limit to the list of units. If I add a new ad unit, the plugin "erase" one of the list. We looked up and if we erase one of the list, a previous "deleted" ad unit came back. The impact that we have, is when we are placing the ad unit in the content, the dropdown list only shows the visible ads in the admin, so we are missing some units for specific pages.

It seems that the limit to show are 100 items. Any idea of how to show the complete list of ad units added?

**Comment by claudiulodro** [comment]
100 items is a limit of the WordPress API. We should add handling for it to work correctly if there are more than 100 units, currently there is none.
