### ISSUE TITLE
Add support for fluid ads

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-ads#107]
It's possible to allow fluid ads, where the publisher doesn't have to specify ad sizes. This will be super useful for sites, especially those running programmatic campaigns.

https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-doubleclick-impl/fluid.md

We should add support for this.

**Comment by claudiulodro** [comment]
I think AMP Plus ads will solve this issue well, since the ad sizes are determined after the page has rendered.
