### ISSUE TITLE
Remove slug key-val targeting

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-ads#164]
From @kmwilkerson at https://github.com/Automattic/newspack-ads/pull/78#issuecomment-907284430

> With the slug values, GAM limits it to 40 characters so those longer post titles will only be targetable within GAM using the first 40. For example, slug=programa-nc-hope-aun-acepta-solicitudes-de-ayuda-para-alquiler-con-servicio-en-espanol will have to be targeted as programa-nc-hope-aun-acepta-solicitudes- in GAM. Because of this, I think we should remove 'slug' as a targetable key so as not confuse publishers on why slug targeting doesn't work when they input the whole slug into the targeting picker. Using ID is the best way to go for single page/post targeting!

**Comment by miguelpeixe** [comment]
@kmwilkerson currently there's no way of knowing if the targeted content is a page, post or a custom post type. Do you think in addition to removing the `slug` key, makes sense to also include the `post_type` key?

**Comment by kmwilkerson** [comment]
@miguelpeixe That's a brilliant idea, yes!
