### ISSUE TITLE
Create inventory in GAM

### ISSUE THREAD

**Issue by kmwilkerson** [Automattic/newspack-ads#166]
Any ad units added in Newspack (after publisher has added Newspack as a service account in GAM) should be automatically pushed to GAM when the user clicks Save.

I recommend we only ask for "name", not "name" and "code", and set both fields as the same value when sending to GAM. I've yet to come across a publisher that has chosen to have different values for 'name' vs 'code'. We do not need to pass sizes, as it's an optional field in GAM and the publisher is likely to change the sizes quite often.

**[Creating an ad unit](https://developers.google.com/ad-manager/api/reference/v202108/InventoryService?hl=en#createadunits)**

- parentId - this is a required field, but unique to each pub. We will need to first run [a statement.query to get the AdUnit.parentId](https://developers.google.com/ad-manager/api/reference/v202108/InventoryService#getadunitsbystatement) for the root ad unit and use the parentId found to push the new units.
- name - use value user input into metafield
- adUnitCode - same as name
- targetWindow - always set to `BLANK`

**Comment by adekbadek** [comment]
All done and, but behind the `NEWSPACK_ADS_USE_GAM` feature flag on `master`, but soon behind existence of [service account credentials instead](https://github.com/Automattic/newspack-ads/pull/163)

https://github.com/Automattic/newspack-ads/blob/1237c9007236821a7181f13ada7ca344f314ca66/includes/class-newspack-ads-gam.php#L281-L287

Ad unit code has a unique id appended to prevent conflicts.
