### ISSUE TITLE
amp-sticky-ad not appearing

### ISSUE THREAD

**Issue by jbwhong** [Automattic/newspack-ads#174]
I have been unable to get the amp-sticky-ad to appear when using a 728x90 inventory slot on my Newspack installation using Google Ad Manager. I have successfully integrated Google Ad Manager with the site for other inventory slots both in widgets and in a global position, so I know GAM is working with NewsPack.

## Steps to reproduce the issue
1. create a 728x90 inventory slot in Google Ad Manager.
1. Make an order with a line item that has a 728x90 creative and make sure it can flow into the inventory slot you created. optionally (and perhaps unnecessarily), set the Line Item Type to Sponsorship (4) to make sure it beats any ad networks that may be set up in Google Ad Manager
1. Wait for a while because it can take Google Ad Manager some time to start delivering the ad.
1. in **Newspack>Advertising**, configure Google Ad Manager with the right network code and add the ad unit there
1. in **Newspack>Advertising>Global Settings**, turn on the Sticky ad, say that Google Ad Manager is the provider and choose the Ad unit you just set up
1. Visit the amp version of an article on the website, and make the viewport narrow as if it were on a mobile phone
## What I expected to happen
I expected to see a sticky ad at the bottom of the viewport. I also expected when viewing the source of the page that I would see `<amp-sticky-ad>` somewhere in the body of the HTML, but I didn't see that.
## What actually happened
No sticky ad at the bottom of the viewport, no `<amp-sticky-ad>` in the HTML source
## Details about environment (WordPress version, Newspack version, PHP version, etc.)
Wordpress 5.8.1, Newspack 1.56.0, Newspack Ads 1.16.0, PHP version 7.4.15 (Supports 64bit Values)
Theme versions: Newspack 1.46.0, Newspack Katharine 1.46.0 (I tried with and without Katharine and got the same result)
Plugins: AMP 2.1.4, W3 Total Cache 2.1.8 (but I turned it off and got the same result)

**URL of the site experiencing the issue**: https://outlookbythebay.com/ (you can get AMP versions of pages by adding ?amp=1 to the url)

**Comment by kmwilkerson** [comment]
@jbwhong The sticky ad within Global Settings is currently for mobile only and due to size mapping, the 728x90 creative will be too large to be shown on mobile. However, this issue brings to light that we do not clearly define that this unit is mobile only. I have opened a new issue (#207) to update the name and description of that global placement. Thank you for bringing this to our attention!
