### ISSUE TITLE
Integrate refresh control into ad wizard

### ISSUE THREAD

**Issue by kmwilkerson** [Automattic/newspack-ads#176]
Refresh Control plugin found here: https://wordpress.org/plugins/ad-refresh-control/

If it's possible to integrate all the things that this plugin does within our own Ad Wizard, that would be ideal as it would prevent publisher's from having to navigate to several different plugins to configure their ads and ad behavior. 

[Additions to the plugin](https://github.com/ampproject/amphtml/blob/main/extensions/amp-a4a/refresh.md) are required to accommodate AMP and will only apply to the mobile sticky footer.

**Comment by kmwilkerson** [comment]
@earcos Update: Yes, we are making it so it will work on AMP, but AMP currently only allows for sticky ads to be refreshed (i.e., the mobile sticky footer Newspack placement). If that restriction ever changes, we will update the functionality accordingly.

**Comment by earcos** [comment]
Great. Refreshing the sticky ad goes a long way 😊
