### ISSUE TITLE
Global Settings: Remove WordAds and AdSense

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-ads#23]
Right now, both WordAds and AdSense appear in the options for Global Setting in the Ads Wizard if you have them enabled, but they can't be applied this way yet:

![image](https://user-images.githubusercontent.com/177561/75462070-7f7a8d00-5938-11ea-91e3-e01df07e6a45.png)

They should be hidden from this dropdown for the short-term, until they are completely hooked up.

Edited to add: the 'Configure' links should also be removed from next to these two options when you've enabled them, unless we can link WordAds' Configure link to Jetpack > Settings > Traffic (since you can refine ad placement from there for that option).

**Comment by adekbadek** [comment]
Not reproducible anymore.
