### ISSUE TITLE
CI Tests failing

### ISSUE THREAD

**Issue by miguelpeixe** [Automattic/newspack-ads#232]
`cimg/php` images [recently stopped using PPA in favor of custom compiling PHP](https://github.com/CircleCI-Public/cimg-php/pull/127).

This breaks our tests because [we currently depend on the PPA to install the `soap` dependency](https://github.com/Automattic/newspack-ads/blob/master/.circleci/config.yml#L10), a requirement of `googleads-php-lib`.

We need to figure out a way to install the extension and the image doesn't appear to present a solution. We might need to use a different base image for our tasks. Ideas are welcome!

**Comment by miguelpeixe** [comment]
We should follow this opened issue for a solution as well: https://github.com/CircleCI-Public/cimg-php/issues/132

**Comment by adekbadek** [comment]
Where are the CI jobs failing? I see [latest one](https://app.circleci.com/pipelines/github/Automattic/newspack-ads/555/workflows/fe6a8ca9-2f8d-42cf-8552-a266d415fd12) on `master` is all right.

**Comment by miguelpeixe** [comment]
You can see on #231 or test locally with `circleci local execute --job test-php`

**Comment by miguelpeixe** [comment]
Merging https://github.com/CircleCI-Public/cimg-php/pull/137 resolved this issue, but [surfaced another one](https://app.circleci.com/pipelines/github/Automattic/newspack-ads/573/workflows/7159f72e-7876-4e26-9d42-737647179546/jobs/1544/steps). It's the same issue being experienced at https://github.com/Automattic/newspack-newsletters/pull/622.

**Comment by adekbadek** [comment]
The new issue (the one related to `node-sass`) is fixed on `newspack-newsletters` by updating `@automattic/calypso-build` - see https://github.com/Automattic/newspack-newsletters/pull/625

**Comment by adekbadek** [comment]
This should do it: https://github.com/Automattic/newspack-ads/pull/234
