### ISSUE TITLE
Multiple ads shown for a placement on AMP page

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-ads#236]
Multiple ads with different sizes are shown for placements on AMP page while accessing from Mobile. Non-AMP page are ok.

- Desktop size ad and Mobile ad shown simultaneously for Global: Below Header position

![](https://user-images.githubusercontent.com/7325107/143372707-213676df-57df-4928-8fb6-9b831edaa85e.png)

- Desktop size ad and Mobile ad shown simultaneously for Ad inserted within post with SCAIP

![](https://user-images.githubusercontent.com/7325107/143373017-4777c2c8-adb2-4bcf-b869-b4c712cce03e.png)

- Multiple Mobile ad shown simultaneously for Ad inserted within post with SCAIP

![](https://user-images.githubusercontent.com/7325107/143373255-aa1c6ead-5fc1-4be1-be7e-9dcddf5c1d42.png)

May be related to Content wider than screen issue in Automattic/newspack-theme#1591

**Comment by miguelpeixe** [comment]
This is possibly related to [how the plugin handles responsive ads with AMP](https://github.com/Automattic/newspack-ads/blob/2145ac202978d2e9a7e1b28eb4b1d00b2c5a630a/includes/class-newspack-ads-model.php#L585-L591).

It creates CSS media queries dynamically to control which ads will be displayed on a certain viewport.

Comment pulled from the method's code:
```
// Gather up all of the ad sizes which should be displayed on the same viewports.
// As a heuristic, each ad slot can safely display ads 200px narrower or less than the slot's width.
// e.g. for the following setup: [[900,200], [750,200]],
// We can display [[900,200], [750,200]] on viewports >= 900px and [[750,200]] on viewports < 900px.
```

Please confirm that you don't have any custom CSS overwriting the dynamically generated rules.

If the rules are being applied as designed, can you share the dimensions of the ads that are being displayed and the screen size that is presenting the issue so I can perform some tests?

**Comment by yogeshbeniwal** [comment]
@miguelpeixe Thanks. No custom CSS to override. Dimensions are:

300x50 320x50 728x90 970x90 970x250 for Global: Below Header position.
300x250 336x280 728x90 for within post.

**Comment by yogeshbeniwal** [comment]
@miguelpeixe This issue is resolved by disabling AMP plus mode. As per my understanding AMP plus mode is for standalone mode websites, we are using Transitional mode so no use of that.

**Comment by miguelpeixe** [comment]
The issues you were experiencing were with `define( 'NEWSPACK_AMP_PLUS_ENABLED', true );`?

With AMP Plus the `<amp-ad />` and the custom responsive strategy through media queries are not used. Are you still able to replicate this issue with the latest version?

**Comment by yogeshbeniwal** [comment]
Yes, issue still remains with latest version.

**Comment by miguelpeixe** [comment]
Recapitulating so I can attempt to reproduce, your environment that causes multiple slots being rendered for the same placement is:

 - with `define( 'NEWSPACK_AMP_PLUS_ENABLED', true );`
 - AMP plugin is active and in Transitional mode
 - GAM ad unit with 300x50 320x50 728x90 970x90 970x250 sizes placed under the "Below header" placement

Is the above accurate?

**Comment by yogeshbeniwal** [comment]
That's correct.

**Comment by miguelpeixe** [comment]
I'm still unable to reproduce. Does changing the AMP template mode to Default fixes it?

If possible, please provide a screenshot of the ads elements nodes in your DevTools. Should be either several `<amp-ad />` tags or a `<div />` inside a `<div id="div-gpt-ad-{slot-id}-0" />` element.

**Comment by yogeshbeniwal** [comment]
Multiple reloads are required sometime to see the issue. Below is code for one of ad slot in sidebar, let me know if you need more info.

```
<div class="newspack_global_ad sidebar_sidebar-1 sidebar_sidebar-1-after">
						<div id="div-gpt-amp-site-com_sidebar-616cea7a96f35-a47a08d131-160x600"><amp-ad width="160px" height="600px" type="doubleclick" data-slot="/XXXXXXXXXX/site-com_sidebar-616cea7a96f35" data-loading-strategy="prefer-viewability-over-views" json='{"targeting":{"slug":"slug-1","category":["international","US"],"post_type":"post","ID":46511}}' class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:160px;height:600px" i-amphtml-layout="fixed"></amp-ad></div> <div id="div-gpt-amp-site-com_sidebar-616cea7a96f35-a47a08d131-300x600"><amp-ad width="300px" height="600px" type="doubleclick" data-slot="/XXXXXXXXXX/site-com_sidebar-616cea7a96f35" data-loading-strategy="prefer-viewability-over-views" json='{"targeting":{"slug":"slug-1","category":["international","US"],"post_type":"post","ID":46511}}' data-multi-size="300x250" data-multi-size-validation="false" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:300px;height:600px" i-amphtml-layout="fixed"></amp-ad></div> <div id="div-gpt-amp-site-com_sidebar-616cea7a96f35-a47a08d131-336x600"><amp-ad width="336px" height="600px" type="doubleclick" data-slot="/XXXXXXXXXX/site-com_sidebar-616cea7a96f35" data-loading-strategy="prefer-viewability-over-views" json='{"targeting":{"slug":"slug-1","category":["international","US"],"post_type":"post","ID":46511}}' data-multi-size="300x250,300x600,336x280" data-multi-size-validation="false" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:336px;height:600px" i-amphtml-layout="fixed"></amp-ad></div>		</div>
```

**Comment by miguelpeixe** [comment]
I actually mean "Standard", not "Default". What's your AMP plugin version? Please make sure you have the latest installed.

The rendered HTML suggests that the AMP Plus flag is not being identified properly because it's using `<amp-ad />` tags.

**Comment by yogeshbeniwal** [comment]
Using AMP plugin v2.2.4, which is latest. We don't have plan to move to standalone mode.

> The rendered HTML suggests that the AMP Plus flag is not being identified properly because it's using `<amp-ad />` tags.

Can you pls suggest what could be the reason for this?

**Comment by miguelpeixe** [comment]
> Can you pls suggest what could be the reason for this?

Still a mystery to me...

Here's where the code is picked:
https://github.com/Automattic/newspack-ads/blob/f7fdc03ccdb55d90d3077d9409d796bc589a362c/includes/providers/gam/class-gam-provider.php#L85-L86

The AMP detection method:
https://github.com/Automattic/newspack-ads/blob/f7fdc03ccdb55d90d3077d9409d796bc589a362c/includes/class-core.php#L120-L128

I suggest running tests to see if `Core::is_amp()` is returning the expected value. On AMP Plus it should return `false`.

**Comment by yogeshbeniwal** [comment]
Does AMP Plus has any effect on Transitional mode?

**Comment by yogeshbeniwal** [comment]
Thank you for confirmation, will stick with AMP plus disabled and transitional mode and gradually disable AMP completely. Closing this issue for https://github.com/Automattic/newspack-plugin/discussions/1578 if required in future.
