### ISSUE TITLE
Copy SCAIP logic into plugin

### ISSUE THREAD

**Issue by miguelpeixe** [Automattic/newspack-ads#237]
#228 takes over how [SCAIP](https://github.com/Automattic/super-cool-ad-inserter-plugin) is configured but still relies on its core logic to display the ads within article content.

The idea of copying the plugin's logic and not using it as a different plugin was [suggested by @adekbadek](https://github.com/Automattic/newspack-ads/pull/228#pullrequestreview-815691706) and we should continue this discussion to decide if this is the better approach.

One point against the idea is that ultimately our goal and SCAIP's goal are the same and SCAIP provides the hooks that allow our customization, we are not misusing the plugin's code to make the integration possible. Sharing the core logic for ad display also means sharing improvements coming from Newspack or SCAIP community.

**Comment by kmwilkerson** [comment]
Since a8c is the owner of SCAIP, would our team be responsible for continuing to maintain the plugin or would that go to another team? And if us, does that create duplicate efforts to update our ad injections plus SCAIP?

**Comment by adekbadek** [comment]
We'd be maintaining it. You're right, this would duplicate our efforts and as Miguel says –

> One point against the idea is that ultimately our goal and SCAIP's goal are the same and SCAIP provides the hooks that allow our customization, we are not misusing the plugin's code to make the integration possible.

I'll close it for now.
