### ISSUE TITLE
Remove AdSense and WordAds from ad providers list

### ISSUE THREAD

**Issue by kmwilkerson** [Automattic/newspack-ads#249]
The Google AdSense toggle doesn't currently allow for direct enablement or manual ad placement - it just directs the user to go to SiteKit to enable auto-ads. Similarly with WordAds, enabling this provider here doesn't do anything or allow the user to take advantage of the full set of features.

**Comment by yogeshbeniwal** [comment]
We probably won't need Adsense in future also. Ad Manger serves ads from Adsense as fallback by default.
