### ISSUE TITLE
Problems with sticky ad

### ISSUE THREAD

**Issue by SergioRodriguezSanchez** [Automattic/newspack-ads#261]
Hi,

Since the last update I have problems with the sticky ad in mobile. The div embedded style 'style="display: flex;"' is not showing, so I can't see the ad properly. I checked and I don't know what the problem is. It worked properly before.

¿Do you know if this is an issue with the plugin?

Thanks!

**Comment by kmwilkerson** [comment]
@SergioRodriguezSanchez We aren't able to replicate this issue and see the mobile sticky footer ad rendering on other Newspack sites. Do you still see the click-to-close button, just with an empty/collapsed div?

**Comment by SergioRodriguezSanchez** [comment]
Hi @kmwilkerson! Yes, I am still having the issue, it didn't happened before one of the last newspack-ads plugin update, but maybe it is not because of the plugin. The thing is I don't see and empty div in the 'newspack_global_ad sticky' div, what I don't see is the 'style="display: flex;"'. The 'style' is empty. Also, if I try to force the CSS I can't make the close button work. So I guess maybe it is a JS problem, but I can't find it...

You can see an example here: https://www.enandaluz.es/andalucia-alcanza-el-millon-de-contagios-de-covid-19/

Any idea?

Thanks!

**Comment by kmwilkerson** [comment]
@SergioRodriguezSanchez It looks like there's a display: none on `.newspack_global_ad.sticky` that is being added by JS from a plugin called SiteGround Optimizer
