### ISSUE TITLE
970x90 ads are shown in a 970x250 container

### ISSUE THREAD

**Issue by earcos** [Automattic/newspack-ads#262]
Seems like the plugin is pushing 970x90 ads on a 970x250 container, even when the banner is only defined as a 970x90 size on Google AdManager. It leaves a huge whitespace. If this information is useful, it's happening, on the below header global ad placement.

**Comment by yogeshbeniwal** [comment]
@earcos May be similar to #259

**Comment by earcos** [comment]
Don't think it's the same. Ads are displayed (AMP version, though) but the container is much bigger than the banner

(A 970x250 container for a 970x90 banner)

**Comment by kmwilkerson** [comment]
@earcos AMP ads set a max height based on the largest size that ad unit can accept. Despite what creative size is selected by your ad server to display, the div itself will always be set at the largest size. In your Newspack > Advertising settings, navigate to the _ad unit_ in question and remove 970x250 from its size options.

**Comment by earcos** [comment]
@kmwilkerson I do display 970x250 banners too. So I can't remove that space. But this behaviour doesn't occur with other sizes. For example, 300x250 banners are displayed in the correct container size.
