### ISSUE TITLE
Hide ad for Subscribers or Paid members

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-ads#291]
Feature to automatically hide ads for Subscribers (WooCommerce Subscriptions) or Paid members (WooCommerce Membership) will be a good option.

**Comment by kmwilkerson** [comment]
@yogeshbeniwal While we understand this is a feature that some publishers would like to employ, as an opinionated platform we do not believe this is a strategy that should be used. There are very specific business goals that would merit this strategy, but they only apply to a small population of publishers.

**Comment by yogeshbeniwal** [comment]
Thanks @kmwilkerson. Can you pls put more light on thought process on this conclusion. As readers are getting more concerned about privacy and using ad blockers, this can be a good option for small and medium size publishers to covert this segment of readers to paid members.
