### ISSUE TITLE
"Generate from HTML code" feature

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-ads#39]
For Google Ad Manager ads we simplify the integration process somewhat by only requiring the ad unit code and sizes information, and [our documentation](https://newspack.blog/support/advertising/google-ad-manager/#create-ad-units) helps people to extract that information.

One thing that could make this easier is to add mechanism, within the "add ad unit" screen to allow a user to generate the settings from a pasted-in HTML code. This could accept either the full HTML, or AMP tag version of the code provided by ad manager and parse that to get the required information out into the relevant fields.

This could be useful in cases where publishers don't have access to ad manager themselves for some reason, perhaps because they are using a 3rd party who has only provided them with HTML code.

**Comment by claudiulodro** [comment]
The Ads Push will automatically pull in ad units, so dealing with or understanding HTML won't be needed! :)
