### ISSUE TITLE
Link to an "advertising" page alongside ad units

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-ads#43]
When displaying ads, publishers may find it useful to provide an link alongside ad units. This could link to a page for two purposes:

1. Explaining to readers why the ad is there, and the publisher's ad policy
2. Informing potential advertisers of the opportunities available to them

This could be something that we just set in the Customiser, with the publisher providing the link text and choosing a page it should link to.

**Comment by philipjohn** [comment]
Another benefit this could bring to publishers is the ability to advertise an "ad-free" experience.

**Comment by claudiulodro** [comment]
With the new block-widget editor in WP 5.8, this can be done by putting an ad unit and explainer text inside a group block.
