### ISSUE TITLE
Settings for SCAIP unable to save

### ISSUE THREAD

**Issue by kmwilkerson** [Automattic/newspack-ads#432]
When unchecking the box for legacy widgets and attempting save, the change in settings does not save and reverts to default.

![Screen Shot 2022-06-06 at 11 34 45 AM](https://user-images.githubusercontent.com/20666833/172204804-abcd9c8a-6d48-4c74-9c2a-a84794fbc014.png)

**Comment by miguelpeixe** [comment]
The issue was related to the publisher's database, not the Ads feature.
