### ISSUE TITLE
Unrecoverable error on launch of ads option

### ISSUE THREAD

**Issue by craig02445** [Automattic/newspack-ads#487]
Updated all software as of 8/20/2022, deactivated anything not from Newspack. On self-hosted until funding comes in ... Maybe a php value needs to be increased or something? Definitely on-line and connected. 
![newspack-ads-error](https://user-images.githubusercontent.com/30699748/186002557-61cfd06a-3d27-4fa5-978e-ad4e51b10086.png)

Thank you.

**Comment by miguelpeixe** [comment]
This is a common error while attempting to navigate the Ads dashboard with adblocker. Can you confirm you don't have it enabled or have whitelisted the site?

**Comment by craig02445** [comment]
Duh. lol.  I turned off my ad blocker and it is working. THANK YOU.
-Craig
