### ISSUE TITLE
Only display Ad Label setting if AMP Plus enabled

### ISSUE THREAD

**Issue by kmwilkerson** [Automattic/newspack-ads#494]
Since the ad label setting won't work on AMP, let's only show that field when AMP Plus is enabled.

**Comment by miguelpeixe** [comment]
This is actually true for every current Ad setting. Should we just hide all settings on AMP and as a consequence, also hide the "Settings" nav menu?

**Comment by kmwilkerson** [comment]
Yeah good suggestion @miguelpeixe I think that's the best way to prevent confusion!

**Comment by miguelpeixe** [comment]
It is actually the other way around. The custom label is supported on AMP, but not the other settings.
