### ISSUE TITLE
Responsive ads

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-ads#51]
We should follow the [GAM guide to implementing responsive ads](https://developers.google.com/doubleclick-gpt/guides/ad-sizes#responsive_ads). I think this could be done in a fully automated way using the existing Ads wizard with no new UI needed: For each breakpoint, add the configured ad sizes that are smaller than it. 

For example, if our mobile breakpoint is `780px`, and our ad sizes are `[[920,100],[320,100]]`, we would show both of those sizes on desktop and only the ones that fit on mobile e.g:

```
var mapping = googletag.sizeMapping()
  .addSize([780, 0],[[920,100],[320,100]])
  .addSize([0, 0], [[320,100]])
  .build();
```

There are a few other considerations, like not showing mobile ads on desktop, but this should at least prevent desktop ads from displaying on mobile. 

Related to #50, some further discussion there.

**Comment by jeffersonrabb** [comment]
For historical reference, the notes in https://github.com/Automattic/newspack-ads/pull/19 are valuable for understanding how we ended up where we did on responsive ad handling.
