### ISSUE TITLE
Allow attributes to be added to Doubleclick AMP ad units' markup

### ISSUE THREAD

**Issue by dero** [Automattic/newspack-ads#55]
Currently, the AMP markup for doubleclick ad units [has a firm structure](https://github.com/Automattic/newspack-ads/blob/e98b0fc0c573b80820802db50148f50af968f956/includes/class-newspack-ads-model.php#L390) that doesn't allow 3rd parties to change the generated markup (AFAIK, let me know if this is incorrect).

In our case we're running a native AMP site and would like to create a child theme and change the units' markup to potentially contain [`rtc-config`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/rtc-documentation.md) and / or [`data-multi-size`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-doubleclick-impl/multi-size.md) attributes to increase ad demand competition, but we're unable to easily do so.

Would it be possible to [make the generated AMP ad unit string filterable](https://github.com/Automattic/newspack-ads/blob/e98b0fc0c573b80820802db50148f50af968f956/includes/class-newspack-ads-model.php#L397)? Or do you consider a filter like that to be too powerful and we should look for other options?

**Comment by kmwilkerson** [comment]
Closing this issue as Newspack is in the process of moving away from AMP
