### ISSUE TITLE
Use plugin functionality to hide ads on Sponsored Content

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-ads#62]
Right now we're working on a feature to allow posts to be marked as 'Sponsored Content' (either by being assigned a sponsored taxonomy, or by being assigned a specific sponsor). This option is being managed in a plugin that is currently under development. 

Part of this will include either fully hiding ads on sponsored content (or adding an option in the Sponsored Content plugin). 

Is it possible to either automatically toggle ads off on posts when they've been assigned a sponsored taxonomy, or a direct sponsor? 

![image](https://user-images.githubusercontent.com/177561/89073929-3e940380-d330-11ea-971a-7d0ef111ea9b.png)

**Comment by adekbadek** [comment]
Closed in https://github.com/Automattic/newspack-sponsors/issues/8
