### ISSUE TITLE
Request for guidance on displaying Adsense ads.

### ISSUE THREAD

**Issue by TheVikrantAdams** [Automattic/newspack-ads#642]
On the advertising screen, only two ad providers are available: Ads Manager and Bradstreet. Adsense is missing. Could you please guide me on how to display ads from Adsense?

![Screenshot_21](https://user-images.githubusercontent.com/130600585/231560862-0cec42dd-c6c8-4fe4-9efa-326346bb56ab.png)

**Comment by kmwilkerson** [comment]
Hi @TheVikrantAdams -- We recommend using Google Site Kit for placing AdSense on your site. You can then control the placement via the AdSense dashboard. However, if you wish to do custom placements with ad tags generated by AdSense, using custom HTML blocks will be the best route.
