### ISSUE TITLE
Responsive AMP ad blocks

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-ads#83]
There should be responsive handling for the ad blocks in AMP mode. Currently there isn't, and the ad just gets cut off by the screen.

**Comment by claudiulodro** [comment]
Related issue for non-AMP responsive ads: https://github.com/Automattic/newspack-ads/issues/51

**Comment by claudiulodro** [comment]
Might be able to do something with [fluid layout](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-doubleclick-impl/fluid.md), possibly combined with [multi-size ads](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-doubleclick-impl/multi-size.md)

**Comment by claudiulodro** [comment]
The only really good solution here that I've been able to figure out is AMP Plus using the non-AMP ad handling. Then it works nicely. Since this bug doesn't affect in-content ads injected via SCAIP, it's not a huge issue.

**Comment by claudiulodro** [comment]
I dont think it makes sense to have responsive ad blocks after https://github.com/Automattic/newspack-ads/pull/98. The logic would get weird. Responsive ad blocks can be achieved where necessary by placing two ad units next to each other and hiding/showing the appropriate unit based on viewport size with some custom CSS.

**Comment by claudiulodro** [comment]
Since Ad blocks are primarily used on homepages, after further thinking it does make sense to make them responsive. As far as I can tell, there is no ad placement that wouldn't be improved if the ad was responsive.

**Comment by miguelpeixe** [comment]
The block was refactored to work with the Placements system and its unified per-provider rendering strategy.
